### ISSUE TITLE
引入之后按照demo使用，只出现这样一个框，没用内容，也无法使用

### ISSUE THREAD

**Issue by slixina** [AnOrdinaryMan/taro-region-picker#1]
![image](https://user-images.githubusercontent.com/49421399/71541134-0211bb00-298f-11ea-9db1-9f2ac30595f3.png)

**Comment by lizesheng0313** [comment]
我是在支付宝引用的， 多了一行字 点击无任何变化  
![image](https://user-images.githubusercontent.com/23352222/80856227-8f855480-8c7a-11ea-8d2c-257cac79cc24.png)

**Comment by lizesheng0313** [comment]
看了下源码 onClick事件多写了一个state 
![image](https://user-images.githubusercontent.com/23352222/80856314-703af700-8c7b-11ea-99d0-3a0edbdda0fb.png)
this.state.onClick 改成  this.onClick 就可以了
